### ISSUE TITLE
Modern Beta type worlds made in 1.20.1 or previous versions cannot be loaded in 1.21.

### ISSUE THREAD

**Issue by Daralexen05** [BlueStaggo/moderner-beta#10]
[message (1).txt](https://github.com/user-attachments/files/16344034/message.1.txt)
I tried loading my Modern Beta 1.7.3 world made in 1.20.1 from April of this year to continue the world into 1.21. However, I get an error message of "java.lang.IllegalStateException: Overworld settings missing" when I try to load the world into 1.21. I tried doing the "Make a new world with the same seed then transfer the regions folder to the new world" method. It somewhat worked, but every biome in the world was incorrectly labelled as Plains and The Void instead of the Beta biomes. This does not only apply to Modern Beta 1.7.3 worlds, but to Modern Infedev and Indev worlds as well. I tried to load a throwaway Modern Infdev world made in 1.20.4, and that did not load in 1.21 as well.

**Comment by BlueStaggo** [comment]
Yeah that's because icanttellyou changed the mod id... next update will have a datafixer in place though

**Comment by hi-skittles** [comment]
so thats why 1.4.0 literally cannot load _any_ world generated with _any_ previous version of the mod? sorry but, the hell lmfao?

**Comment by BlueStaggo** [comment]
@hi-skittles As I said, the mod ID was changed.

**Comment by nerddude24** [comment]
can confirm this as well, also tried the latest build from Github Actions but still didn't work, hope this gets fixed soon.

**Comment by hi-skittles** [comment]
> @hi-skittles As I said, the mod ID was changed.

not doubting, just seems a bit silly to me to change something that breaks all previous world gens made with the mod. no worries though, will wait until it gets fixed.

**Comment by BlueStaggo** [comment]
Datafixers suck so uhh no more luck here

**Comment by Xrey274** [comment]
So it's not possible to do it? I'm not knowledgeable on Minecraft modding, but just translating the namespace for the biomes from one to another doesn't sound too hard?
