### ISSUE TITLE
Generation Type Minecraft PE Shouldn’t Be Infinite

### ISSUE THREAD

**Issue by Big1N** [BlueStaggo/moderner-beta#14]
I love Everything About this mod it’s just when I select the Generation Type to be minecraft Pocket Edition it generates it as an infinite world and this in my opinion ruins the nostalgia of Minecraft pe because the Minecraft pe alpha back them has a world boarder. No matter what I do and how hard I try configure it the settings it keeps generating infinite and if I select the chunk prefectures to classic which has the same world size as Minecraft pe it doesn’t generate pe it just generates classic. 

If you could change the chunk provider from minecraft Pocket Edition Alpha to have endless ocean like the minecraft classic chunk provider it would would make the minecraft Pocket Edition to be 100 percent 1 to 1 with the real world boarder like it always had back then. It would mean so much to me and other veterans of the minecraft pocket edition community if you fixed this issue with the minecraft pocket edition chunk preset to not be infinite and to have a border where land stops generating to finish the nostalgia. Thanks for the awesome mod and keep up the good work.

**Comment by xp2-882030kgz010602** [comment]
I have felt the opposite way: It seems clear that the world could continue, instead of just stopping at an arbitrary limit. That being said, have you considered using `/worldborder`?
