### ISSUE TITLE
discussion: can u add more terrain generation?

### ISSUE THREAD

**Issue by xiaoxiaogtlao** [BlueStaggo/moderner-beta#15]
can u add pocket edition world generation like 0.12 0.16 or others? 
and xbox too

**Comment by BlueStaggo** [comment]
PE world gen is basically 1.12 world generation but seeded differently.
For Xbox, I guess you could just reduce the biome size.

**Comment by xiaoxiaogtlao** [comment]
and also pls make a setting so I can set the depth to 0 in minecraft world, and then I can also decide whether to include deepslate on the layer.
because I want to mining diamonds without deepslate at y=12, because deepslate is really hard and slows down my speed of finding diamonds.
and if I want deepslate later, I can open the map on normal version
