### ISSUE TITLE
(CRASH) Exception generating new chunk

### ISSUE THREAD

**Issue by vinnyg0621** [BlueStaggo/moderner-beta#21]
[crash report](https://mclo.gs/YMpB18H)

steps to reproduce:
1. press "create new world"
2. select worldtype "moderner beta"
3. select "1.0"
4. turn climatic biomes to "on"
5. edit biomes
6. create new world

**Comment by BlueStaggo** [comment]
Could you do this again and provide the full log? I can't exactly figure it out from the crash report.

**Comment by vinnyg0621** [comment]
okay this mod is completely broken now, it crashed when I didn't turn climatic biomes to on. here is the [report](https://mclo.gs/15zoaha) and the [log](https://mclo.gs/IpdQdJW)

**Comment by forkiesassds** [comment]
Should be fixed in the next version.
