### ISSUE TITLE
More graphics-related tweaks

### ISSUE THREAD

**Issue by faradey8951** [BlueStaggo/moderner-beta#22]
I assume it should be able to activate some special tweaks directed to specific version type you choose like:
 - Clouds height should be at Y:128 on some of versions
 - Fog start/end position related to render distance (take attention on fog mechanics up to release 1.6.4, it's just like on Minecraft Legacy Console Edition)
 - Old villages type
 - Old tallgrass shader type (more dark-colored)
 - Old lighting mechanics at all and specifically at leaves (it should be somewhere darker, somewhere lighter)

**Comment by BlueStaggo** [comment]
Well, this mod is mostly focused on world generation and stuff like resource packs and Nostalgic Tweaks can already do most of this stuff. As for old villages, someone already made a datapack for that and it has been updated for 1.21: https://www.planetminecraft.com/data-pack/classic-villages/
