### ISSUE TITLE
Default Presets?

### ISSUE THREAD

**Issue by FR00TP3NCH** [BlueStaggo/moderner-beta#23]
so uhh i was wondering if you can like add an option in the config to make a preset for moderner beta default because i have no idea how to use datapacks

**Comment by BlueStaggo** [comment]
Sorry, but the official way to do it is to use a datapack. It'd quite easy to do really if you have experience with JSON: simply make a replacement for `data/moderner_beta/worldgen/world_preset/moderner_beta.json`. The original JSON can be found in the mod jar.
