### ISSUE TITLE
[Request and/or question] Options for Swiss Cheese caves and height limit

### ISSUE THREAD

**Issue by TheInsane101** [BlueStaggo/moderner-beta#26]
Moderner Beta might be my favourite mod I've ever found, and the little time it took to get updated to 1.21.4 amazed me! 

There are just two small things I want to ask about. IDK if they are already in the mod, because I am very inexperienced and new to Minecraft Java edition and don't understand what all of the options in the customisation config do. Sorry if these are dumb questions:

In multiple of TheMisterEpic's videos, he mentioned how Minecraft's caves used to have many more branches and connections before the release 1.7 update in 2013, explaining how 1.7 reduced the number and sizes of caves that could be generated, making them more boring and less intimidating. The last Minecraft version to have a compatible mod that restores these "Swiss cheese" caves (due to their previously greater density) is 1.12.2, and as far as I know, no mod has restored these caves for 1.13 to 1.17. My question is whether these caves are also restored in the pre-1.7 presets in Moderner Beta, or if they can be added in a later update. I tried testing and comparing worlds generated with pre-1.7 and post-1.7 presets, but I am finding it difficult to tell the difference. Could I please get confirmation on this?

My other question is whether the mod has an option to decrease the vertical size of worlds; more specifically, prevent terrain from generating below y=0. It's great that the pre-1.18 caves generate below y=0, allowing us to experience the more modern cave features in the old-style caves and explore them deeper, but I think adding an option to change the vertical height to be more accurate to pre-1.18 can greatly improve immersion for those that want it. Does this already exist and I have simply not identified which toggle or slider can apply this option? 

Thank you to anyone who answers these dumb questions of mine!

**Comment by forkiesassds** [comment]
Yes. Pre-1.7 caves are in this mod and are used within the Early Release presets. In addition if you enable beta caves with fixed caves enabled on other presets you can have these types of caves on any other preset. And yes, if you use the reduced height datapack you can make the world have the pre-1.18 height.

**Comment by TheInsane101** [comment]
Thank you for answering everything! Appreciate it!

**Comment by TheInsane101** [comment]
Ok, I just did more tests seeing if I could enable 1.7's caves on beta presets, and it doesn't seem to be an option. (Unmined was used for viewing all the worlds below)

Here I generated two 1.17.1 preset worlds with the same seed, with the bottom map having all cave modes enabled (the Major release presets have "force beta caves" disabled by default):
![1 17 1](https://github.com/user-attachments/assets/cd0fb252-ce72-4f99-9416-385614043fbc)
![1 17 1 Swiss cheese](https://github.com/user-attachments/assets/464839ed-0310-4d65-acdb-21365cf3bab3)

Doing this experiment for the 1.6.4 preset showed that the 1.7 caves could be enabled on Early Release presets (Early Release presets have all cave options enabled by default; the bottom image showing 1.7 caves happens when you disable "Force beta caves":)
![1 6 4 all caves](https://github.com/user-attachments/assets/d7a8cf8b-3b96-4aa9-b46b-167385223b34)
![1 6 4 no fixed caves](https://github.com/user-attachments/assets/27d52524-1000-4f73-99c7-833b4465de61)

However, repeating this experiment for the Beta 1.7.3 preset showed that disabling "force beta caves" did not change the caves at all. Toggling off any of the other cave modes, even multiple, changed nothing either, implying that adding 1.7's caves to Beta presets is not possible?
Top to bottom: All cave modes on, beta caves off, fixed caves off, beta canyons off, all cave modes off
![Beta all caves](https://github.com/user-attachments/assets/232cec7d-69ec-4850-b18a-cd3fcff5458b)
![Beta no beta caves](https://github.com/user-attachments/assets/e08309e9-440e-4575-8ac1-bb3c5b03df59)
![Beta no fixed caves](https://github.com/user-attachments/assets/f019cc53-24a9-42a3-ba86-87d2db5b99e0)
![Beta no beta canyons](https://github.com/user-attachments/assets/a0d4768e-701a-466e-9baa-c430ad7d0a10)
![Beta no cave modes](https://github.com/user-attachments/assets/cd4d8e05-7c74-44e6-98ad-a4d20c00a5ca)

Is it possible to try 1.7's caves on Beta presets, and how? I would read the [Modern Beta Wiki](https://github.com/b3spectacled/modern-beta-fabric/wiki) for this information, but as indicated by [this issue submission on that original version of the mod](https://github.com/b3spectacled/modern-beta-fabric/issues/59), the original developer never implemented the pre-1.7 caves as an option. Did you implement these cave options yourself when forking and extending this mod?
