### ISSUE TITLE
[Bug?] Disabling beta caves in early and major release presets removes all caves

### ISSUE THREAD

**Issue by TheInsane101** [BlueStaggo/moderner-beta#28]
I noticed that when you create a new world with the beta 1.8.1 to release 1.17.1 presets with the "force beta caves" option disabled but every other cave toggle enabled in the chunk options, all caves stop generating except the pools, underground structures and ravines. This only happens in the latest version of this mod. Since the 1.12 and 1.17.1 presets have beta caves disabled by default, this means that they lack caves by default unless you're aware of this bug and enable the beta caves to fix it.

1.21.4, Major Release 1.17.1 preset by default ("force beta caves" toggled off):
![2024-12-12_14 46 01](https://github.com/user-attachments/assets/54a3f55c-e31f-4093-85c4-523c7d4ea638)

Same preset, seed and x & z coordinates as the previous screenshot above, except in the 1.21.3 version of the mod:
![2024-12-12_14 50 51](https://github.com/user-attachments/assets/ea8b9ff1-836c-4bd6-b0cd-7d96e8e3cd9d)

Disabling beta caves in Beta world presets still generates the caves, meaning only the release presets have this bug.

Assuming this is a bug, is this cave config supposed to generate the 1.7.2 - 1.17.1 caves?

**Comment by forkiesassds** [comment]
Unable to reproduce. You sure this isn't a conflict with other mods? Please send full logs if possible as these can help find the root cause.

**Comment by TheInsane101** [comment]
Wait, I JUST realise it's because I had left the No Caves mod on, which messed with this. Sorry for this mistake!
