### ISSUE TITLE
World Generation not working, suddenly

### ISSUE THREAD

**Issue by RubyTheQuester** [BlueStaggo/moderner-beta#30]
I'm not sure exactly what is causing this, but I can no longer generate a world using modern-er beta.

This is the error I keep getting, not sure what it means since this error only start happening randomly.

> "java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.m_203656_(net.minecraft.tags.TagKey)" because the return value of "mod.bluestaggo.modernerbeta.world.biome.provider.fractal.BiomeInfo.biome()" is null"

[crash-2024-12-22_20.37.53-server.txt](https://github.com/user-attachments/files/18224139/crash-2024-12-22_20.37.53-server.txt)
Full log attached

**Comment by forkiesassds** [comment]
Update Moderner Beta to 2.1.2.
