### ISSUE TITLE
Setting hill size to 0 causes the moderner-beta mod to crash

### ISSUE THREAD

**Issue by Delvin4519** [BlueStaggo/moderner-beta#4]
The crash occurred since I was trying to use the pre-existing settings to emulate LCE biome generation. Scaling a layer 0 times is needed in order to recreate LCE biome generation (In this case I selected the 1.17.1 preset, set hill size to 0 instead of 2, and it causes the mod to crash)

The normal world generation in Java 1.17.1 is as follows:

Biome 1:256  -> scale 2x = Biome 1:64
RiverHills 1:256 -> scale 2x = Hills 1:64 & River 1:64
BiomeHills 1:64 -> scale 4x = BiomeHills 1:4
RiverHills 1:64 -> scale 4x = RiverHills 1:4
Ocean 1:256 -> scale 6x = Ocean 1:4

On Legacy Console Edition, the scaling for biomes requires the use of scaling a layer 0 times as noted below:

Biome 1:256  -> **scale 0x = Biome 1:256**
RiverHills 1:256 -> scale 2x = Hills 1:64 & River 1:64
BiomeHills 1:64 -> scale 4x = BiomeHills 1:4
RiverHills 1:64 -> scale 4x = RiverHills 1:4

(I don't have enough info on aqautic update oceans on LCE, but it would be best to add a dedicated scaling options for oceans to set ocean size)

Minecraft 1.17.1/1.12.2 modded using MCP or MCP-reborn allow the option of scaling a layer 0 times without crashing the game. LCE was the same.

![image](https://github.com/user-attachments/assets/de7dbc65-b92f-4278-ad56-82b9ba2d8611)

**Comment by forkiesassds** [comment]
The bug has been fixed in the next upcoming release of the mod.
