### ISSUE TITLE
Crash upon launching for the first time with Moderner Beta (Forge 1.20.1)

### ISSUE THREAD

**Issue by Karthsteel** [BlueStaggo/moderner-beta#7]
Forge 1.20.1, mod version Moderner Beta 1.4.0+1.20.1. Game crashes with a "Failed to load colormap texture" error upon first launch of the game without having ran it before. Once I removed the mod, booted up my pack, and put it back in, it worked mostly fine. [Here is the crash report.](https://pastebin.com/dzA7q3Cu)

**Comment by forkiesassds** [comment]
Cannot reproduce.
