### ISSUE TITLE
Sand refuses to generate. (Forge 1.20.1)

### ISSUE THREAD

**Issue by Karthsteel** [BlueStaggo/moderner-beta#8]
That's... pretty much it. Looked for beaches, and, well, sand doesn't generate. Deserts are simply grass.
![2024-07-16_17 07 47](https://github.com/user-attachments/assets/4f643d07-54f1-4421-94c9-422e0fab9c6d)

**Comment by forkiesassds** [comment]
Unable to reproduce. What preset are you using and what other mods are you using?

**Comment by BlueStaggo** [comment]
Incompatibility with the Blueprint API mod. Gonna close this for now because this isn't really in my control.
